### ISSUE TITLE
Feature request: Convert HTML emails to Plain Text

### ISSUE THREAD

**Issue by jrief** [ui/django-post_office#117]
This feature shall be optional, configurable through a settings variable. If activated, it will require BeautifulSoup.

If the text body of an email template is empty, but the HTML body is filled, then convert the rendered HTML to text. This proposed feature also fixes #116. If it will be accepted, I can implement it.

**Comment by selwin** [comment]
I'm planning on reworking parts of this library so it can handle not just emails, but other types of messages like `sms` or push notifications.

I don't think this feature is desirable because it can be done easily by the user himself and don't want to pull in too many email specific functionalities.

Thanks for the idea though.

**Comment by jrief** [comment]
> I don't think this feature is desirable because it can be done easily by the user himself and don't want to pull in too many email specific functionalities.

@selwin and how would you do that? Is there any hook which can be used to plug in a functionality converts a HTML email into plain text?

**Comment by ui** [comment]
```python
def my_send_mail(...):
    mail.send(html_message=html_message, message=strip_html(html_message), ...)
```

**Comment by racitup** [comment]
Just found this and thought I'd include a [link to my gist](https://gist.github.com/racitup/2ded9c06c2563049e7e12b25bf2a8369) that will provide a better output than beautifulsoup.text.
I'm not sure if an approach like this could be used to convert the html template rather than the rendered output...
