### ISSUE TITLE
Gmail considers post_office insecure

### ISSUE THREAD

**Issue by b509** [ui/django-post_office#173]
If I try to send a mail via my gmail account, I get a mail warning me of an insecure app trying to access the account. This attempt is refused and the mail thus not sent. I get an entry in my post_office_log with the following fields:

exception_type= 

> SMTPAuthenticationError

message= 

> (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuY\n5.7.14 vhi_daWaxF3MiLqUZqZMKvn4K8LC6WsiPQn_QdetfGuVAPDnYMQ7iTnv2f2zxv8qXkIrKp\n5.7.14 UsFijh37AYuwEGHnLQz0SpLOHe0guDjoK-w7C9Xo2WNVJnvsYu9eBKIoGpgokuyFpjA42V\n5.7.14 U43k73D_REE0HsIwmoUbJiDPQVtRzkOygnud7b4rzpyfsbFBxAxW2S5fyy2EwxZeVV3NfC\n5.7.14 1BZOQ_Q_wPnRyMvuXkHYdeHf1irgc> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 e5sm8243333wma.13 - gsmtp')

I can tell Gmail to give insecure apps access, but I'd rather not and would be glad if you find a way to fix this. I am using post_office 2.0.8 and django 1.10.1 .

**Comment by selwin** [comment]
Communication with mail servers is not something this library is made to tackle. You should investigate your options and if needed, you could tell post office use a custom email backend by setting the EMAIL_BACKEND parameter.

**Comment by iragm** [comment]
Posting from the future, because this issue came up when searching for an error.

Gmail is disabling less secure apps at the end of May, 2022, but you can work around this in Django by setting an application password.

This process is actually quite easy: https://suhailvs.github.io/blog02.html

You need to enable an application-specific password in Gmail, and then set up Django's settings.py to look like this:

```
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'your-username@gmail.com'
EMAIL_HOST_PASSWORD = 'Application spectific password that you made in gmail'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
```
