### ISSUE TITLE
Consider making EmailTemplate.name unique

### ISSUE THREAD

**Issue by SeiryuZ** [ui/django-post_office#347]
We've hit an issue where duplicate EmailTemplate.name crash the mail.send 

Should we consider, making EmailTemplate.name unique?

**Comment by jrief** [comment]
There is a pull request for this issue: #346

I would like to have one name per natural language for each template (say "Welcome", "Selamat datang", "Bienvenido", etc.) and a machine readable identifier for each template (say "welcome_email").

Apparently we haven't found a consensus about that yet.

**Comment by SeiryuZ** [comment]
Ah OK. Thanks for the prompt reply on this @jrief !

I'll close this issue as to not split the discussion to here. Thanks again!

**Comment by jrief** [comment]
@SeiryuZ sorry, had a typo in the pull request number above. 

Anyway, since you are a maintainer of django-post_office yourself, please have a second look at my pull request #324 , eventually add your comments and/or approve it. I just have seen the the migration files are out of date, hence the unit tests fail. If you agree on my approach, I will fix them as soon as possible in order to create a mergeable pull request.
