### ISSUE TITLE
Migration 0011 error

### ISSUE THREAD

**Issue by jamescw** [ui/django-post_office#95]
Hitting this migration error today, anyone else experience this?

```
Running migrations for post_office:
 - Migrating forwards to 0011_auto__chg_field_email_context.
 > post_office:0011_auto__chg_field_email_context
FATAL ERROR - The following SQL query failed: ALTER TABLE "post_office_email" ALTER COLUMN "context" TYPE json, ALTER COLUMN "context" DROP NOT NULL, ALTER COLUMN "context" DROP DEFAULT;
The error was: column "context" cannot be cast automatically to type json
HINT:  Specify a USING expression to perform the conversion.
```

**Comment by selwin** [comment]
Hi there, looking at the error log, it seems like `jsonfield` is trying to change the column type to `json` type instead of usualy text field. I also ran into this issue before but upgrading to the latest version of `jsonfield` fixed it. 

There's a similar issue here: https://github.com/bradjasper/django-jsonfield/issues/67
